version: "3.9"

services:
  nest-api:
    container_name: backend-nest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SOROBAN_RPC_MAINNET=${SOROBAN_RPC_MAINNET}
    ports:
      - 3000:3000
    env_file:
      - .env
